### ISSUE TITLE
No database backup in 2.6.1.

### ISSUE THREAD

**Issue by sfaessler** [jdaehne/BackupMODX#10]
I've installed the plugin checked both MySQL Database and files and clicked "Backup Site" - backup works and is stored in the directory but there is no MySQL Database there. 

If I only check and click "Backup Site" it reloads and shows text "No Backup" - Is that a bug with current version?

Thanks for your help.

**Comment by jdaehne** [comment]
To make Database Backups possible your server has to support "executing a shell command". Is that possible on your environment?

**Comment by Jako** [comment]
This should be solved with 3.0.0. Please reopen the issue, if thats not the case.
