### ISSUE TITLE
Problem to unzip backup file

### ISSUE THREAD

**Issue by mediengaarage** [jdaehne/BackupMODX#14]
I always have problems to unzip the created zipped files (for example XYZ_files.tar).
I use WinZip.  
This is the error message:

```
Fehler: Das System kann den angegebenen Pfad nicht finden.
kann D:\...\core\packages\contentblocks-1.7.5-pl\modCategory\cdecf9112376ad7249b9dfe6be8023c8\0\contentblocks\model\vendor\modmore\alpacka\core\components\alpacka\vendor\composer\autoload_namespaces.php nicht erstellen
Schwerer Fehler: Dateierstellung fehlgeschlagen.
```
Where could this be the problem?
Is there a possibility to create a .zip file instead of .tar?

**Comment by sebastian-marinescu** [comment]
Maybe it's a limitation of path-length in your Windows-system? 
Could you try extracting it on a Linux-machine?

**Comment by mediengaarage** [comment]
Thank you for the tipp. I don't have a Linux-machine. I will see how to deactivate the path-length in my Windowssystem.

**Comment by sebastian-marinescu** [comment]
Here are some ways to do that: 
https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

**Comment by mediengaarage** [comment]
Thank you! It works!
