### ISSUE TITLE
2.0.0: Two widgets if upgraded from 1.x

### ISSUE THREAD

**Issue by mcnickel** [jdaehne/BackupMODX#15]
First: Thank you for this great extra - and version 2! :smile:  

The widget name changed from "Backup MODX" to "BackupMODX". On upgrade, this causes, I assume, the creation of a new/second widget.

**Comment by jdaehne** [comment]
![image](https://user-images.githubusercontent.com/10563227/50558327-7159be00-0ced-11e9-827d-38073bd19aab.png)
@mcnickel ok, thanks for the report. Have to fix that.

**Comment by Jako** [comment]
This should be solved with 3.0.0.
