### ISSUE TITLE
adjustments for all-inkl.com

### ISSUE THREAD

**Issue by jenswittmann** [jdaehne/BackupMODX#2]
Hello,
thanks for the great extra. It works very well!

But, to use it on a all-inkl.com Shared-/Root-Host you have to activate "/bin/pktar" as alias for "tar" (line 88/93) over the support. Maybe you can add a note in the docs.

Thanks very much for this extra!
Jens

**Comment by jdaehne** [comment]
Hi Jens,

thanks a lot for your nice feedback and your solution for all-inkl-server. I will immediately put that in the docs.

I also added the property-setting "tarAlias" to the snippet, so we don't have to edit the snippet code every time there is an update for the extra. So the widget should work even after updating now.

thanks a lot for that issue... hope that will work as planed. :-)

nice regards,
Jan

**Comment by jenswittmann** [comment]
Perfect Jan!
