### ISSUE TITLE
Download Hangs

### ISSUE THREAD

**Issue by EkoOne** [jdaehne/BackupMODX#20]
BackupMODX 2.0.1
Revo 2.7.0

I no longer get the AJAX error in v2.0.1 but the backup still hangs. The progress animation has been running for over 2 hours and it still hasn't completed on v.2.7.0. I've tried three different browsers and it's the same problem.

**Comment by terrybarth** [comment]
Modx 2.6.5
BackupModx 2.0.01
Hosting is on Skytoaster
PHP 5.6.40
Memory Limit 128M
Max execution time 360

I have two sites where this is not completing correctly. 

On one of my sites (refenced above), the backup works when I select just the database and I can download the file, file looks good.

However, when I select the files only backup, I get the Ajax Failing message, the progress animation continues until I reload the page. There is a folder and a zip file in my designated backup folder (assets/backup). However, if I attempt to download the zip file from the file manager, I get page not working message at this URL: 

`http://xxxxxxxxxx/connectors/index.php?action=browser/file/download&download=1&file=assets/backups/2019-02-18--184944--f028/2019-02-18--184944--f028.zip&HTTP_MODAUTH=modx5b562eb37ea2a3.64806931_15c6afe3dbebbf7.05598003&source=1&wctx=undefined.
`
If I attempt to download the zip file via the download icon in the widget, Chrome says "download.php Failed- Server problem". I am able to download the file via ftp and unzip with no errors. Files all seem to be intact.

I found this in the error log:

[2019-02-18 18:47:02] (ERROR @ /home/xxxxxx/public_html/core/components/backupmodx/model/backupmodx/backupmodx.class.php : 98) PHP warning: filesize(): stat failed for /backups/2019-02-18--184702--8472/2019-02-18--184702--8472.sql

**Comment by Jako** [comment]
This should be solved with 3.0.0. Please reopen the issue, if thats not the case.
