### ISSUE TITLE
Feature Request: Lexicon Entries

### ISSUE THREAD

**Issue by EkoOne** [jdaehne/BackupMODX#21]
I realize this may sound silly but a client inquired about it.

Would it be possible to add a few Lexicon entries so the text on the widget can be edited? I have a client who is _very_ particular and loves that MODX allows the editing of Lexicon entries. I told him it's not currently possible with BackupMODX but I thought I would ask just in case it was something you could add.

Specifically he would like to edit/change the following:

- Backup your MODX-Site:
- Backup Site!
- Restore a Backup

By the way, I know I could manually edit the text myself but it will just get overwritten the next time the Extra is updated. And I really don't want to do it over and over again.

**Comment by Jako** [comment]
This should be solved with 3.0.0. There is a Crowdin translate project available: https://crowdin.com/project/backupmodx
