### ISSUE TITLE
Duplicate BackupMODX widgets

### ISSUE THREAD

**Issue by ant-tar** [jdaehne/BackupMODX#24]
I've tried this twice on different MODX websites (2.7.0), issue is actual.
in Panels I see two widgets BackupMODX and Backup MODX after upgrade from 1.0.5 up to 2.0.1 version

![default](https://user-images.githubusercontent.com/2815640/53287119-e9da7980-3788-11e9-97cd-c5806214ff08.png)

**Comment by Jako** [comment]
Should be solved with 3.0
