### ISSUE TITLE
No Database backup

### ISSUE THREAD

**Issue by iWatchYouFromAfar** [jdaehne/BackupMODX#25]
I will describe my actions. Developed a subdomain site, on a different database. After the site was uploaded to the working domain, changed the path, changed the configuration files and changed the settings to a new (clean) database. There are no errors, the site works well on a new basis.

But when I try to create a backup of the database, I get a file of 0 megabytes. Please tell me what and where can it work wrong? After all, the site itself works well, the paths are all correct and both databases are on the same server.

P.S.
Files backup works fine!

I will be glad to any answer!

MODX 2.7.1
BackupMODX 2.0.1 PL
PHP 7.2
MySQL 5.7.21-20

Thanks!

**Comment by jeffmiranda** [comment]
This may be related to issue #23
