### ISSUE TITLE
function close()

### ISSUE THREAD

**Issue by ryube801960** [jdaehne/BackupMODX#33]
I always get the error message "Uncaught Error: Call to a member function close()" when I try to backup files, but fine with database.

**Comment by dev7apps** [comment]
Same issue here.
Uninstalled and reinstalled. No luck. Enabled debugging, but nothing logged. DB backup alone is fine.

Full Error:
```
Uncaught Error: Call to a member function close() on string in /pathtocore/core/components/backupmodx/vendor/chumper/zipper/src/Chumper/Zipper/Zipper.php:67 
Stack trace: 
#0 /pathtocore/core/components/backupmodx/src/Backup/Backup.php(114): Chumper\Zipper\Zipper->__destruct() 
#1 /pathtocore/core/components/backupmodx/src/Backup/Backup.php(222): BackupMODX\Backup\Backup->backupFiles('2019-08-08--185...') 
#2 /pathtocore/core/components/backupmodx/processors/backup.class.php(42): BackupMODX\Backup\Backup->backup(true, false, '') 
#3 /pathtocore/model/modx/modprocessor.class.php(177): BackupMODXBackupProcessor->process() 
#4 /pathtocore/core/model/modx/modx.class.php(1764): modProcessor->run() 
#5 /pathtocore/core/model/modx/modconnectorresponse.class.php(144): modX->runProcessor('backup', Array, Array) 
#6 /pathtocore/core/model/modx/modconnectorrequest.class.php(86): modConnectorResponse->outputContent(Array) 
#7 /pathtocore/core/model/modx/modconnec
```
MODX Revolution 2.7.1-pl
Ubuntu 16
Php 7

**Comment by des-yogi** [comment]
I have a similar error!
MODX Revolution 2.7.1-pl
Ubuntu 16
Php 7.1
Older versions worked fine on this server

**Comment by Jako** [comment]
I am not sure whats going wrong there. Please look into the backupmodx.targetPath system setting. Does it point to `{core_path}backup/` or elsewhere? Is that target a folder and is it writable?

There should be a backupmodx.log in core/cache/logs if you enable the debug option. Is the target folder included in the file list?

**Comment by Jako** [comment]
You could add the following patch to log the target in core/cache/logs/backupmodx.log

https://github.com/jdaehne/BackupMODX/commit/504ec092b26fd2a531713088a551461e88e47b84

**Comment by rharrell-southern** [comment]
I can confirm this is still an issue, I'm on 
MODX Revolution 2.7.1-pl
PHP Version 7.2.19

Backup config path is default, I just did a wipe and clean install on BackupMODX.
Sql backs up fine, but the process that zips up the system files seems to be failing, with the error message listed above. After the job fails I can see the folder for the job, as well as the sql file, but no zip file in the output directory.  Seems like it might be an error in the Chumper script, or possibly an error in how it is called?

**Comment by rharrell-southern** [comment]
Ahh, got it figured out. You need the library PHP-zip installed.  In Ubuntu, just do:

`sudo apt-get install php-zip`

Here's the reference from Chumper's github issue tracker where I found the solution: https://github.com/Chumper/Zipper/issues/103

**Comment by Jako** [comment]
This execption was not catched. It should be catched with https://github.com/jdaehne/BackupMODX/pull/41/commits/e80ee9ea9e97ac385a1f63af8d7aa962ebd74f99
