### ISSUE TITLE
dashboard didn't show up

### ISSUE THREAD

**Issue by ryube801960** [jdaehne/BackupMODX#37]
I just have a clean installation of modx 2.7.1-pl. After installed, I install the backupmodx extra immediatly and add the widget to the dashboard. However, the widget didn't show up on the dashboard.
![擷取](https://user-images.githubusercontent.com/53134523/64589770-7fadbd00-d3d8-11e9-8719-f1a18fac8bb0.PNG)
![擷取](https://user-images.githubusercontent.com/53134523/64589722-5e4cd100-d3d8-11e9-8f55-2bd0459d7cb2.PNG)

**Comment by Jako** [comment]
Are there any errors in the browser console?

**Comment by vrdriver** [comment]
Same thing has happened for me. It's not appearing either.
Version: 2.8.3-pl 
There are no listed errors in the console, nor php errors (that I could see).

**Comment by Jako** [comment]
Is this issue fixed with 3.0.5?

**Comment by Jako** [comment]
Closing due to lack of response. Please reopen this if the issue still exist.
