### ISSUE TITLE
Does not backup files

### ISSUE THREAD

**Issue by Hal100000** [jdaehne/BackupMODX#4]
I just installed BackupMODX on a all-inkl hosted site. The MySQL Database backup is working without any problem - however after the backup it shows:

`Backup Finished!
MySQL:d01f643a_20160227-141948_mysql.sql (3.45 MB)
Files:No Backup!`

**Comment by jdaehne** [comment]
Hi,
to use it on a all-inkl.com Shared-/Root-Host you have to activate "/bin/pktar" as alias for "tar". You can set that in the snippet-properties.

best regards...
Jan

**Comment by Hal100000** [comment]
I changed that setting already. Didn't change the situation.

**Comment by jdaehne** [comment]
Hi,
than i guess your hosting-server does not support to tar files. Did you ask your provider?

**Comment by Hal100000** [comment]
My hosting provider is all-inkl.
And It seems like all-inkl does not have tar or pktar installed anymore ...

But I found a solution using PEAR:
`@error_reporting(E_ALL ^ E_WARNING ^ E_DEPRECATED);`
`@ini_set("max_execution_time", 300);`
`@ini_set("memory_limit", "256M");`
`$v_list = array();`
`$path = preg_replace('/(\/www\/htdocs\/\w+\/).*/', '$1', realpath(__FILE__));`
`$ignore = array($targetPath, "cache");`
`if (!empty($_POST["files"])){`
`array_push($v_list,$base_path);`
`array_push($v_list,$core_path);`
`}`
`if (file_exists($targetTxt)) {`
`array_push($v_list,$targetTxt);`
`}`
`if (file_exists($targetSql)) {`
`array_push($v_list,$targetSql);`
`}`
`include "Archive/Tar.php";`
`$archiv = new Archive_Tar($targetCom, true);`
`$archiv->setIgnoreList($ignore);`
`$archiv->createModify($v_list, "", $path);`

Only the ignore stuff is only working for directories like "cache" but not for directory tress like "/www/bla/blub/cache". Do you have any idea?

**Comment by sebastian-marinescu** [comment]
On my all-inkl machine via SSH I typed `which tar`, which gave me "/bin/tar". 

I provided that as the setting, but the files-backup still doesn't work. 
Nothing in the MODX error-log.

**Comment by AK-2063** [comment]
Doesn't backup files.
MODX Revo 2.7.1
PHP 7.0.33-0 + deb9u3
I create a backup database and files, but I have files (0).
No errors, but ... backupmodx.class.php: 67) PHP warning: filesize (): statistics failed for /var/www/...backups/....zip - it does not exist.
I just fixed the problem - I installed Zip.
I think it will help someone.

**Comment by Jako** [comment]
This should be solved with 3.0.0. Please reopen the issue, if thats not the case.
