### ISSUE TITLE
Error creating target path

### ISSUE THREAD

**Issue by rharrell-southern** [jdaehne/BackupMODX#40]
I did a fresh install of 3.0.0 and when I try to run it from the home screen I get "Error creating target path!" as the result. I checked and nginx has write access to the folder I specified during the install.

**Comment by Jako** [comment]
PHP needs write access to that folder.

**Comment by rharrell-southern** [comment]
Yes, PHP has write access to the directory I set during the configuration. I can create files there using the ModX file browser.

**Comment by rharrell-southern** [comment]
Ah, nevermind, I did a full uninstall and a clean reinstall and it seems to be working now. Not sure what happened.

**Comment by Jako** [comment]
What is your backupmodx.targetPath system setting? Is that folder writable and could it be 'executed'?
