### ISSUE TITLE
dublicates in core

### ISSUE THREAD

**Issue by Vpered4** [jdaehne/BackupMODX#5]
Hello. In my backups i have dublicates of all filtes in core.
http://f-picture.net/lfp/s019.radikal.ru/i620/1604/6e/f5c387dab78c.png/htm
So my backup tar size is 267 Мb. Extrackt with replacement 158 Mb.
Dublicates are only in core folder. I use default params of snippet.

**Comment by jdaehne** [comment]
Hello Vpered4,
i just checked this on different sites on different hosting-systems, but i can't reproduce this behavior. I always get an exact copy of all files without duplicates.
Sorry, but i don't have any idea why that happens on your system...

nice regards,
Jan

**Comment by Vpered4** [comment]
I deleted $core_path from [135 line](https://github.com/jdaehne/BackupMODX/blob/master/core/components/backupmodx/elements/snippets/backupmodxwidget.snippet.php#L135)
and it's worked for me. Now no dublicates.
Maybe because i have permission in core 755.

Thank you!

**Comment by jdaehne** [comment]
Hi Vpered4,
yes, this is probably the causing code-part. If you have your core-folder inside the base-folder, the core-folder gets defined twice in the tar-line.
I just tried it on some sites an still didn't get duplicates. Maybe your hosting-system handles it differently.

The script should may check if the core-folder is inside the base-folder and then not include that one again. I will do that in the next version.

Thanx for the report.

jan

**Comment by Jako** [comment]
Should be solved with 3.0.0
