### ISSUE TITLE
Specify Folders to Backup?

### ISSUE THREAD

**Issue by terrybarth** [jdaehne/BackupMODX#6]
Is there a way to limit the backup to a selected folder on the server? I have a server I use as a sandbox of sorts that has a bunch of folders. Some of them have other Modx installations, some have other completely unrelated content. So when I run the backup, it gobbles up everything on the server, when I really just want one particular Modx installation. The resulting file can be really big.

I see there is an exclude folders parameter, but it seems I would have list every other folder in the root of the server. It would be great to specify the folder to be backed up.

Perhaps this is a one off situation for most people. I just thought I'd check.

Thanks again for a great tool!

**Comment by jdaehne** [comment]
Hi terrybarth,

right now, there is no option for choosing just specific files to backup. I will put that one on my todo-list and try to find a solution for that.

best regards
Jan

**Comment by terrybarth** [comment]
Wow. I wasn't expecting to add to you to do list! Certainly this is not an urgent issue, I can easily make my zip files from my host. While you're in there, it might be cool to be able to specify zip or tar compression.  Can I send you a beer?

**Comment by Jako** [comment]
There is a backupmodx.excludeFiles and backupmodx.excludeFolders system setting since 3.0.0.
