### ISSUE TITLE
Text description is not generated

### ISSUE THREAD

**Issue by Advanc8d** [jdaehne/BackupMODX#64]
When you fill in the **Add a readme file** text box, a backup is created, but the description is not. MODX 2.8.1, PHP Version 7.3.11, BackupMODX 3.0.2-pl.

![image](https://user-images.githubusercontent.com/2069227/111776798-7fdb2280-88c3-11eb-976d-e41e23d6e154.png)

**Comment by Jako** [comment]
Fixed with 3.0.3
