### ISSUE TITLE
Backup site actions view visible after backup

### ISSUE THREAD

**Issue by lektriq** [jdaehne/BackupMODX#65]
When backup is made, the initial “Backup your site” action view is retained below the backup finished/download buttons. Noted running BackupMODX 3.0.2-pl on MODX 2.8.1 and 2.8.2.

![backupmodx-rendering-bug](https://user-images.githubusercontent.com/7228750/117287588-6afe2280-ae62-11eb-9158-df15b597ebbb.png)

**Comment by Jako** [comment]
Fixed with 3.0.3
