### ISSUE TITLE
Cleaning backups

### ISSUE THREAD

**Issue by ovomatik** [jdaehne/BackupMODX#68]
Hello. Thanks for your modx plugin.

I have a problem with BackupModx, or maybe a logical I don't understand.
I use the plugin with a cronjob. I activate the option for files and database to be clean when a same number limit is reached. For me it would be logical to only have the older files erased. But instead all files and the backup folder are deleted.

Do I have forgot something?

**Comment by Jako** [comment]
This will be fixed with the upcoming 3.0.5.
