### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by terrybarth** [jdaehne/BackupMODX#7]
I just tried to backup a site and got this message in the widget. The DB was not backed up.

`Usage: mysqldump [OPTIONS] database [tables] OR mysqldump [OPTIONS] --databases [OPTIONS] DB1 [DB2 DB3...] OR mysqldump [OPTIONS] --all-databases [OPTIONS] For more options, use mysqldump --help`

This appeared in the modx error log.

`[2016-04-28 14:14:06] (ERROR @ /homexxx/xxxxxxx/public_html/core/cache/includes/elements/modsnippet/57.include.cache.php : 117) PHP warning: filesize(): stat failed for /homexxx/xxxxxxx/public_html/assets/backup/xxxxxxxx_modx2_20160428-141406_mysql.sql`

When I manually exported the DB it was 22mb.

Hostmonster Shared hosting
Modx 2.4.2
PHP Ver 5.4.43

**Comment by terrybarth** [comment]
Just backed up another site.  Backup was successful. I found this in the error log.
`[2016-04-28 14:42:55] (ERROR @ /xxxxx/xxxxxx/public_html/core/cache/includes/elements/modsnippet/48.include.cache.php : 117) PHP warning: filesize(): stat failed for /xxxxx/xxxxxx/public_html/assets/backup/xxxxxxx_modx_20160428-144255_mysql.sql`

Sql files 17mb.

Same environment as previous, different account.

**Comment by terrybarth** [comment]
Backed up yet another site in the same type of environment as the two above. No error messages. The sql file size 25mb.

Of course this is what happens normally. I'm using this on more than a dozen sites. The two error message above have never come up before today.

**Comment by Mayanktaker** [comment]
[2019-08-10 22:19:58] (ERROR @ /home/mysite/public_html/core/components/backupmodx/src/Backup/Backup.php : 109) PHP warning: filesize(): stat failed for /home/mysite/public_html/assets/backup/2019-08-10--221958--54d1/2019-08-10--221958--54d1.zip

Note : Sql is backing up successfully. 
php 7.2
Modx 2.7.1
Memory 120M
Max upload size 10M

**Comment by Jako** [comment]
This should be solved with 3.0.0. Please reopen the issue, if thats not the case.
