### ISSUE TITLE
Update from 3.0.3 to 3.0.4 not running

### ISSUE THREAD

**Issue by marcelfischer71** [jdaehne/BackupMODX#70]
After download the package, installation breaks every time at the same point:

`Attempting to preserve files at /usr/local/www/apache24/noexec/www.....de/core/components/backupmodx into archive /usr/local/www/apache24/noexec/www.....de/core/packages/backupmodx-3.0.4-pl/modCategory/c2c106616dd2f4b8a6ff1432dc0cb872.1.preserved.zip`

MODX-Version: 2.8.3
PHP: 7.3

**Comment by Jako** [comment]
Where is your backup folder located? Is it maybe inside of `core/components/backupmodx/`? If yes, thats the issue. The preserving tries to pack the old version of the package and the preserved zip can grow very large, containing the backups.

**Comment by marcelfischer71** [comment]
Yes, that is the backup folder. What is the solution? Change directory?

**Comment by Jako** [comment]
Move it to `core/backup` and reference that folder in the system settings.

**Comment by marcelfischer71** [comment]
Ok, that works
