### ISSUE TITLE
Downloading database file from dashboard saves page template

### ISSUE THREAD

**Issue by valokammi** [jdaehne/BackupMODX#9]
Hi.
First of all. Thanks for this extra! Does its job nice and smooth. With Bob Rays UpgradeModx, Modx now have tools that should be in core for years.

But I have issue that might be a dangerous for backup purposes. Happened in multiple sites.

When try to download database file from dashboard link, downloads file is containing error page template code. Method to download is click with second mouse button and "Save target to disk...". If you accidentally click link normal way, it returns 404 error page.

Database file size shows as it should be in dashboard, but downloaded file is small. And when file is opened in notepad it is sites error page template code.

Other downloads ok from dashboard. In combined file database was ok.

From file tree all downloads ok.

System info:
BackupModx: 1.0.5-beta
MODX Revolution 2.5.7-pl (traditional)
Apache version 2.4.12 
PHP Version: 5.4.42
Database type: mysql
System: Linux 2.6.32-642.4.2.el6.x86_64

**Comment by Jako** [comment]
That should be solved with 3.0.0. Please reopen this issue, if that's not the case.
